### ISSUE TITLE
Old libraries in requirements

### ISSUE THREAD

**Issue by kamran-redis** [RedisVentures/ray-feast#1]
Hi I am trying to setup the project on Ubuntu 20.04.5 LTS. But the python libraries have a clash.

Setup:
Python 3.8.10
"Ubuntu" "20.04.5 LTS (Focal Fossa)"

Issue 1: Feast 0.24 is no longer compatible with this repo. I had to use `feast==0.23.2` for  `init-fs`  and `test-fs` to work 
Issue 2: When running `make train` I get the following error.
```
~/ray-feast/feature_repo# make train
 predictions: [9.8514730e-01 4.2677217e-04 1.4235990e-04 ... 1.6891042e-03 8.4638423e-01
 9.9973881e-04]
Numpy array precision: 1.0
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    result = round(xgboost_cls.predict(loan_request))
  File "train.py", line 121, in predict
    data = xgb.DMatrix(data=features_df, enable_categorical=True)
  File "/root/ray-feast/venv/lib/python3.8/site-packages/xgboost/core.py", line 575, in inner_f
    return f(**kwargs)
  File "/root/ray-feast/venv/lib/python3.8/site-packages/xgboost/core.py", line 686, in __init__
    handle, feature_names, feature_types = dispatch_data_backend(
  File "/root/ray-feast/venv/lib/python3.8/site-packages/xgboost/data.py", line 889, in dispatch_data_backend
    return _from_pandas_df(data, enable_categorical, missing, threads,
  File "/root/ray-feast/venv/lib/python3.8/site-packages/xgboost/data.py", line 344, in _from_pandas_df
    data, feature_names, feature_types = _transform_pandas_df(
  File "/root/ray-feast/venv/lib/python3.8/site-packages/xgboost/data.py", line 282, in _transform_pandas_df
    _invalid_dataframe_dtype(data)
  File "/root/ray-feast/venv/lib/python3.8/site-packages/xgboost/data.py", line 246, in _invalid_dataframe_dtype
    raise ValueError(msg)
ValueError: DataFrame.dtypes for data must be int, float, bool or category.  When
categorical type is supplied, DMatrix parameter `enable_categorical` must
be set to `True`. Invalid columns:bankruptcies, credit_card_due, hard_pulls, missed_payments_1y, missed_payments_2y, missed_payments_6m, mortgage_due, student_loan_due, vehicle_loan_due
make: *** [Makefile:39: train] Error 1
```

**Comment by tylerhutcherson** [comment]
Looks like issues with our requirements.txt and env setup
